package httpapi
import("encoding/json";"errors";"net/http";"strings";"github.com/danielschillem/KALAN-SIRA/internal/academic";"github.com/danielschillem/KALAN-SIRA/internal/billing";"github.com/danielschillem/KALAN-SIRA/internal/enrollment";"github.com/danielschillem/KALAN-SIRA/internal/payment";"github.com/danielschillem/KALAN-SIRA/internal/school";"github.com/danielschillem/KALAN-SIRA/internal/student")
type Router struct{schools *school.Service;academics *academic.Service;students *student.Service;enrollments *enrollment.Service;billing *billing.Service;payments *payment.Service}
func NewRouter(s *school.Service,a *academic.Service,st *student.Service,e *enrollment.Service,b *billing.Service,p *payment.Service)http.Handler{r:=&Router{s,a,st,e,b,p};m:=http.NewServeMux();m.HandleFunc("GET /health",r.health);m.HandleFunc("POST /api/v1/schools",r.createSchool);m.HandleFunc("GET /api/v1/schools/{publicID}",r.getSchool);m.HandleFunc("POST /api/v1/school-years",r.createSchoolYear);m.HandleFunc("POST /api/v1/levels",r.createLevel);m.HandleFunc("POST /api/v1/classes",r.createClass);m.HandleFunc("POST /api/v1/students",r.createStudent);m.HandleFunc("POST /api/v1/guardians",r.createGuardian);m.HandleFunc("POST /api/v1/student-guardians",r.linkGuardian);m.HandleFunc("POST /api/v1/enrollments",r.createEnrollment);m.HandleFunc("POST /api/v1/fee-schedules",r.createFeeSchedule);m.HandleFunc("POST /api/v1/fee-items",r.createFeeItem);m.HandleFunc("POST /api/v1/installment-plans",r.createPlan);m.HandleFunc("POST /api/v1/installments",r.createInstallment);m.HandleFunc("POST /api/v1/enrollments/activate",r.activateEnrollment);m.HandleFunc("POST /api/v1/payment-intents",r.createPaymentIntent);m.HandleFunc("POST /api/v1/payments/cash",r.recordCash);return m}
func(r *Router)health(w http.ResponseWriter,_ *http.Request){writeJSON(w,200,map[string]string{"status":"ok","service":"kalan-sira-api","version":"0.5.0"})}
func decode(w http.ResponseWriter,q *http.Request,v any)bool{d:=json.NewDecoder(http.MaxBytesReader(w,q.Body,1<<20));d.DisallowUnknownFields();if d.Decode(v)!=nil{writeError(w,400,"invalid_request","invalid JSON body");return false};return true}
func(r *Router)createSchool(w http.ResponseWriter,q *http.Request){var i school.CreateInput;if !decode(w,q,&i){return};o,e:=r.schools.Create(q.Context(),i);created(w,o,e,"school_create_failed")}
func(r *Router)getSchool(w http.ResponseWriter,q *http.Request){o,e:=r.schools.GetByPublicID(q.Context(),strings.TrimSpace(q.PathValue("publicID")));if errors.Is(e,school.ErrNotFound){writeError(w,404,"school_not_found","school not found");return};if e!=nil{writeError(w,500,"internal_error","unable to load school");return};writeJSON(w,200,o)}
func(r *Router)createSchoolYear(w http.ResponseWriter,q *http.Request){var i academic.CreateSchoolYearInput;if !decode(w,q,&i){return};o,e:=r.academics.CreateSchoolYear(q.Context(),i);created(w,o,e,"school_year_create_failed")}
func(r *Router)createLevel(w http.ResponseWriter,q *http.Request){var i academic.CreateLevelInput;if !decode(w,q,&i){return};o,e:=r.academics.CreateLevel(q.Context(),i);created(w,o,e,"level_create_failed")}
func(r *Router)createClass(w http.ResponseWriter,q *http.Request){var i academic.CreateClassInput;if !decode(w,q,&i){return};o,e:=r.academics.CreateClass(q.Context(),i);created(w,o,e,"class_create_failed")}
func(r *Router)createStudent(w http.ResponseWriter,q *http.Request){var i student.CreateStudentInput;if !decode(w,q,&i){return};o,e:=r.students.CreateStudent(q.Context(),i);created(w,o,e,"student_create_failed")}
func(r *Router)createGuardian(w http.ResponseWriter,q *http.Request){var i student.CreateGuardianInput;if !decode(w,q,&i){return};o,e:=r.students.CreateGuardian(q.Context(),i);created(w,o,e,"guardian_create_failed")}
func(r *Router)linkGuardian(w http.ResponseWriter,q *http.Request){var i student.LinkGuardianInput;if !decode(w,q,&i){return};if e:=r.students.LinkGuardian(q.Context(),i);e!=nil{writeError(w,400,"guardian_link_failed",e.Error());return};writeJSON(w,201,map[string]string{"status":"linked"})}
func(r *Router)createEnrollment(w http.ResponseWriter,q *http.Request){var i enrollment.CreateInput;if !decode(w,q,&i){return};o,e:=r.enrollments.Create(q.Context(),i);created(w,o,e,"enrollment_create_failed")}
func(r *Router)createFeeSchedule(w http.ResponseWriter,q *http.Request){var i billing.CreateFeeScheduleInput;if !decode(w,q,&i){return};o,e:=r.billing.CreateFeeSchedule(q.Context(),i);created(w,o,e,"fee_schedule_create_failed")}
func(r *Router)createFeeItem(w http.ResponseWriter,q *http.Request){var i billing.CreateFeeItemInput;if !decode(w,q,&i){return};o,e:=r.billing.CreateFeeItem(q.Context(),i);created(w,o,e,"fee_item_create_failed")}
func(r *Router)createPlan(w http.ResponseWriter,q *http.Request){var i billing.CreatePlanInput;if !decode(w,q,&i){return};o,e:=r.billing.CreatePlan(q.Context(),i);created(w,o,e,"installment_plan_create_failed")}
func(r *Router)createInstallment(w http.ResponseWriter,q *http.Request){var i billing.CreateInstallmentInput;if !decode(w,q,&i){return};o,e:=r.billing.CreateInstallment(q.Context(),i);created(w,o,e,"installment_create_failed")}
func(r *Router)activateEnrollment(w http.ResponseWriter,q *http.Request){var i billing.ActivateEnrollmentInput;if !decode(w,q,&i){return};o,e:=r.billing.ActivateEnrollment(q.Context(),i);if e!=nil{writeError(w,400,"enrollment_activation_failed",e.Error());return};writeJSON(w,200,o)}
func(r *Router)createPaymentIntent(w http.ResponseWriter,q *http.Request){var i payment.CreateIntentInput;if !decode(w,q,&i){return};o,e:=r.payments.CreateIntent(q.Context(),i);created(w,o,e,"payment_intent_create_failed")}
func(r *Router)recordCash(w http.ResponseWriter,q *http.Request){var i payment.CashInput;if !decode(w,q,&i){return};o,e:=r.payments.RecordCash(q.Context(),i);if e!=nil{writeError(w,400,"cash_payment_failed",e.Error());return};writeJSON(w,201,o)}
func created(w http.ResponseWriter,o any,e error,c string){if e!=nil{writeError(w,400,c,e.Error());return};writeJSON(w,201,o)}
func writeJSON(w http.ResponseWriter,s int,v any){w.Header().Set("Content-Type","application/json; charset=utf-8");w.WriteHeader(s);_ = json.NewEncoder(w).Encode(v)}
func writeError(w http.ResponseWriter,s int,c,m string){writeJSON(w,s,map[string]any{"error":map[string]string{"code":c,"message":m}})}
