package httpapi
import("net/http";"github.com/danielschillem/KALAN-SIRA/internal/academic";"github.com/danielschillem/KALAN-SIRA/internal/billing";"github.com/danielschillem/KALAN-SIRA/internal/enrollment";"github.com/danielschillem/KALAN-SIRA/internal/notification";"github.com/danielschillem/KALAN-SIRA/internal/payment";"github.com/danielschillem/KALAN-SIRA/internal/portal";"github.com/danielschillem/KALAN-SIRA/internal/student")
func(r *Router)tenantSchoolYear(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i academic.CreateSchoolYearInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.academics.CreateSchoolYear(q.Context(),i);created(w,o,e,"school_year_create_failed")}
func(r *Router)tenantLevel(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i academic.CreateLevelInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.academics.CreateLevel(q.Context(),i);created(w,o,e,"level_create_failed")}
func(r *Router)tenantClass(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i academic.CreateClassInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.academics.CreateClass(q.Context(),i);created(w,o,e,"class_create_failed")}
func(r *Router)tenantStudent(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i student.CreateStudentInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.students.CreateStudent(q.Context(),i);created(w,o,e,"student_create_failed")}
func(r *Router)tenantEnrollment(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i enrollment.CreateInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.enrollments.Create(q.Context(),i);created(w,o,e,"enrollment_create_failed")}
func(r *Router)tenantFeeSchedule(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i billing.CreateFeeScheduleInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.billing.CreateFeeSchedule(q.Context(),i);created(w,o,e,"fee_schedule_create_failed")}
func(r *Router)tenantFeeItem(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i billing.CreateFeeItemInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.billing.CreateFeeItem(q.Context(),i);created(w,o,e,"fee_item_create_failed")}
func(r *Router)tenantPlan(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i billing.CreatePlanInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.billing.CreatePlan(q.Context(),i);created(w,o,e,"installment_plan_create_failed")}
func(r *Router)tenantInstallment(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i billing.CreateInstallmentInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.billing.CreateInstallment(q.Context(),i);created(w,o,e,"installment_create_failed")}
func(r *Router)tenantActivateEnrollment(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i billing.ActivateEnrollmentInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.billing.ActivateEnrollment(q.Context(),i);if e!=nil{writeError(w,400,"enrollment_activation_failed",e.Error());return};writeJSON(w,200,o)}
func(r *Router)tenantCash(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i payment.CashInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.payments.RecordCash(q.Context(),i);if e!=nil{writeError(w,400,"cash_payment_failed",e.Error());return};writeJSON(w,201,o)}
func(r *Router)tenantPaymentLink(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i portal.CreateLinkInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.portal.CreateLink(q.Context(),i);created(w,o,e,"payment_link_create_failed")}
func(r *Router)tenantNotification(w http.ResponseWriter,q *http.Request){sid,_:=schoolPrincipal(q);var i notification.QueueInput;if !decode(w,q,&i){return};i.SchoolPublicID=sid;o,e:=r.notifications.Queue(q.Context(),i);created(w,o,e,"notification_queue_failed")}
