package parent

import(
 "context"
 "fmt"
 "time"
 "github.com/jackc/pgx/v5/pgxpool"
)
type Service struct{db *pgxpool.Pool}
func NewService(db *pgxpool.Pool)*Service{return &Service{db:db}}
type Child struct{StudentPublicID string `json:"student_public_id"`;StudentName string `json:"student_name"`;SchoolPublicID string `json:"school_public_id"`;SchoolName string `json:"school_name"`;ClassName string `json:"class_name"`;Balance int64 `json:"balance"`;NextDueDate *time.Time `json:"next_due_date,omitempty"`;NextDueAmount int64 `json:"next_due_amount"`}
type Dashboard struct{GuardianPublicID string `json:"guardian_public_id"`;GuardianName string `json:"guardian_name"`;TotalBalance int64 `json:"total_balance"`;Children []Child `json:"children"`}
type Charge struct{ID string `json:"id"`;Label string `json:"label"`;Amount int64 `json:"amount"`;Paid int64 `json:"paid"`;Balance int64 `json:"balance"`;DueDate *time.Time `json:"due_date,omitempty"`;Status string `json:"status"`}
type Payment struct{PublicID string `json:"public_id"`;Amount int64 `json:"amount"`;Method string `json:"method"`;Status string `json:"status"`;PaidAt *time.Time `json:"paid_at,omitempty"`;ReceiptNumber string `json:"receipt_number,omitempty"`}
type ChildDetail struct{Child Child `json:"child"`;Charges []Charge `json:"charges"`;Payments []Payment `json:"payments"`}
func(s *Service)Dashboard(ctx context.Context,guardianPublicID string)(Dashboard,error){var d Dashboard;e:=s.db.QueryRow(ctx,`SELECT public_id,concat_ws(' ',first_name,last_name) FROM guardians WHERE public_id=$1`,guardianPublicID).Scan(&d.GuardianPublicID,&d.GuardianName);if e!=nil{return d,e};rows,e:=s.db.Query(ctx,`SELECT st.public_id,concat_ws(' ',st.first_name,st.last_name),sc.public_id,sc.name,c.name,COALESCE(sum(ch.balance),0),min(ch.due_date) FILTER(WHERE ch.balance>0),COALESCE((SELECT ch2.balance FROM student_charges ch2 JOIN enrollments e2 ON e2.id=ch2.enrollment_id WHERE e2.student_id=st.id AND e2.status='ACTIVE' AND ch2.balance>0 ORDER BY ch2.due_date NULLS LAST LIMIT 1),0) FROM student_guardians sg JOIN guardians g ON g.id=sg.guardian_id JOIN students st ON st.id=sg.student_id JOIN schools sc ON sc.id=st.school_id LEFT JOIN enrollments e ON e.student_id=st.id AND e.status='ACTIVE' LEFT JOIN classes c ON c.id=e.class_id LEFT JOIN student_charges ch ON ch.enrollment_id=e.id AND ch.status<>'CANCELLED' WHERE g.public_id=$1 GROUP BY st.id,sc.id,c.id ORDER BY sc.name,st.last_name,st.first_name`,guardianPublicID);if e!=nil{return d,e};defer rows.Close();for rows.Next(){var c Child;if e=rows.Scan(&c.StudentPublicID,&c.StudentName,&c.SchoolPublicID,&c.SchoolName,&c.ClassName,&c.Balance,&c.NextDueDate,&c.NextDueAmount);e!=nil{return d,e};d.TotalBalance+=c.Balance;d.Children=append(d.Children,c)};return d,rows.Err()}
func(s *Service)Child(ctx context.Context,guardianPublicID,studentPublicID string)(ChildDetail,error){var out ChildDetail;e:=s.db.QueryRow(ctx,`SELECT st.public_id,concat_ws(' ',st.first_name,st.last_name),sc.public_id,sc.name,c.name,COALESCE(sum(ch.balance),0),min(ch.due_date) FILTER(WHERE ch.balance>0),COALESCE((SELECT ch2.balance FROM student_charges ch2 JOIN enrollments e2 ON e2.id=ch2.enrollment_id WHERE e2.student_id=st.id AND e2.status='ACTIVE' AND ch2.balance>0 ORDER BY ch2.due_date NULLS LAST LIMIT 1),0) FROM student_guardians sg JOIN guardians g ON g.id=sg.guardian_id JOIN students st ON st.id=sg.student_id JOIN schools sc ON sc.id=st.school_id LEFT JOIN enrollments e ON e.student_id=st.id AND e.status='ACTIVE' LEFT JOIN classes c ON c.id=e.class_id LEFT JOIN student_charges ch ON ch.enrollment_id=e.id AND ch.status<>'CANCELLED' WHERE g.public_id=$1 AND st.public_id=$2 GROUP BY st.id,sc.id,c.id`,guardianPublicID,studentPublicID).Scan(&out.Child.StudentPublicID,&out.Child.StudentName,&out.Child.SchoolPublicID,&out.Child.SchoolName,&out.Child.ClassName,&out.Child.Balance,&out.Child.NextDueDate,&out.Child.NextDueAmount);if e!=nil{return out,e};cr,e:=s.db.Query(ctx,`SELECT ch.id::text,ch.label,ch.net_amount,ch.amount_paid,ch.balance,ch.due_date,ch.status FROM student_charges ch JOIN enrollments e ON e.id=ch.enrollment_id JOIN students st ON st.id=e.student_id JOIN student_guardians sg ON sg.student_id=st.id JOIN guardians g ON g.id=sg.guardian_id WHERE g.public_id=$1 AND st.public_id=$2 AND e.status='ACTIVE' AND ch.status<>'CANCELLED' ORDER BY ch.due_date NULLS LAST`,guardianPublicID,studentPublicID);if e!=nil{return out,e};for cr.Next(){var c Charge;if e=cr.Scan(&c.ID,&c.Label,&c.Amount,&c.Paid,&c.Balance,&c.DueDate,&c.Status);e!=nil{cr.Close();return out,e};out.Charges=append(out.Charges,c)};cr.Close();pr,e:=s.db.Query(ctx,`SELECT p.public_id,p.amount,p.payment_method,p.status,p.paid_at,COALESCE(r.receipt_number,'') FROM payments p JOIN students st ON st.id=p.student_id JOIN student_guardians sg ON sg.student_id=st.id JOIN guardians g ON g.id=sg.guardian_id LEFT JOIN receipts r ON r.payment_id=p.id WHERE g.public_id=$1 AND st.public_id=$2 ORDER BY p.created_at DESC`,guardianPublicID,studentPublicID);if e!=nil{return out,e};defer pr.Close();for pr.Next(){var p Payment;if e=pr.Scan(&p.PublicID,&p.Amount,&p.Method,&p.Status,&p.PaidAt,&p.ReceiptNumber);e!=nil{return out,e};out.Payments=append(out.Payments,p)};return out,pr.Err()}
type LinkChildInput struct{GuardianPublicID string `json:"guardian_public_id"`;SchoolPublicID string `json:"school_public_id"`;StudentPublicID string `json:"student_public_id"`}
func(s *Service)LinkChild(ctx context.Context,in LinkChildInput)error{tag,e:=s.db.Exec(ctx,`INSERT INTO student_guardians(student_id,guardian_id,relationship,is_primary,can_pay,can_receive_notifications) SELECT st.id,g.id,'PARENT',false,true,true FROM students st JOIN schools sc ON sc.id=st.school_id JOIN guardians g ON g.public_id=$1 WHERE sc.public_id=$2 AND st.public_id=$3 ON CONFLICT(student_id,guardian_id) DO NOTHING`,in.GuardianPublicID,in.SchoolPublicID,in.StudentPublicID);if e!=nil{return e};if tag.RowsAffected()==0{return fmt.Errorf("child not found or already linked")};return nil}
