package auth
import("context";"crypto/rand";"crypto/sha256";"encoding/base64";"encoding/hex";"fmt";"math/big";"time";"github.com/jackc/pgx/v5/pgxpool")
type Service struct{db *pgxpool.Pool}
func NewService(db *pgxpool.Pool)*Service{return &Service{db:db}}
type Principal struct{IdentityID string `json:"identity_id"`;Role string `json:"role"`;GuardianPublicID string `json:"guardian_public_id,omitempty"`;SchoolPublicID string `json:"school_public_id,omitempty"`}
type RequestOTPInput struct{Phone string `json:"phone"`}
type OTPChallenge struct{ChallengeID string `json:"challenge_id"`;ExpiresAt time.Time `json:"expires_at"`;DevelopmentCode string `json:"development_code,omitempty"`}
type VerifyOTPInput struct{ChallengeID string `json:"challenge_id"`;Code string `json:"code"`}
type Session struct{Token string `json:"token"`;ExpiresAt time.Time `json:"expires_at"`;Principal Principal `json:"principal"`}
func h(v string)string{x:=sha256.Sum256([]byte(v));return hex.EncodeToString(x[:])}
func secret()string{b:=make([]byte,32);_,_=rand.Read(b);return base64.RawURLEncoding.EncodeToString(b)}
func code()string{n,_:=rand.Int(rand.Reader,big.NewInt(1000000));return fmt.Sprintf("%06d",n.Int64())}
func(s *Service)RequestOTP(ctx context.Context,in RequestOTPInput)(OTPChallenge,error){if in.Phone==""{return OTPChallenge{},fmt.Errorf("phone is required")};var identity string;e:=s.db.QueryRow(ctx,`SELECT id::text FROM auth_identities WHERE phone=$1 AND status='ACTIVE'`,in.Phone).Scan(&identity);if e!=nil{return OTPChallenge{},e};c:=code();exp:=time.Now().Add(5*time.Minute);var id string;e=s.db.QueryRow(ctx,`INSERT INTO auth_otps(identity_id,code_hash,expires_at) VALUES($1::uuid,$2,$3) RETURNING id::text`,identity,h(c),exp).Scan(&id);if e!=nil{return OTPChallenge{},e};return OTPChallenge{ChallengeID:id,ExpiresAt:exp,DevelopmentCode:c},nil}
func(s *Service)VerifyOTP(ctx context.Context,in VerifyOTPInput)(Session,error){tx,e:=s.db.Begin(ctx);if e!=nil{return Session{},e};defer tx.Rollback(ctx);var identity,stored string;var expires time.Time;var consumed *time.Time;var attempts int;e=tx.QueryRow(ctx,`SELECT identity_id::text,code_hash,expires_at,consumed_at,attempts FROM auth_otps WHERE id=$1::uuid FOR UPDATE`,in.ChallengeID).Scan(&identity,&stored,&expires,&consumed,&attempts);if e!=nil{return Session{},e};if consumed!=nil||time.Now().After(expires)||attempts>=5{return Session{},fmt.Errorf("OTP expired or unavailable")};if h(in.Code)!=stored{_,_=tx.Exec(ctx,`UPDATE auth_otps SET attempts=attempts+1 WHERE id=$1::uuid`,in.ChallengeID);_ = tx.Commit(ctx);return Session{},fmt.Errorf("invalid OTP")};_,e=tx.Exec(ctx,`UPDATE auth_otps SET consumed_at=now() WHERE id=$1::uuid`,in.ChallengeID);if e!=nil{return Session{},e};tok:=secret();sessionExp:=time.Now().Add(24*time.Hour);_,e=tx.Exec(ctx,`INSERT INTO auth_sessions(identity_id,token_hash,expires_at)VALUES($1::uuid,$2,$3)`,identity,h(tok),sessionExp);if e!=nil{return Session{},e};var p Principal;e=tx.QueryRow(ctx,`SELECT ai.id::text,ai.role,COALESCE(g.public_id,''),COALESCE(sc.public_id,'') FROM auth_identities ai LEFT JOIN guardians g ON g.id=ai.guardian_id LEFT JOIN schools sc ON sc.id=ai.school_id WHERE ai.id=$1::uuid`,identity).Scan(&p.IdentityID,&p.Role,&p.GuardianPublicID,&p.SchoolPublicID);if e!=nil{return Session{},e};if e=tx.Commit(ctx);e!=nil{return Session{},e};return Session{Token:tok,ExpiresAt:sessionExp,Principal:p},nil}
func(s *Service)Authenticate(ctx context.Context,token string)(Principal,error){var p Principal;e:=s.db.QueryRow(ctx,`SELECT ai.id::text,ai.role,COALESCE(g.public_id,''),COALESCE(sc.public_id,'') FROM auth_sessions ss JOIN auth_identities ai ON ai.id=ss.identity_id LEFT JOIN guardians g ON g.id=ai.guardian_id LEFT JOIN schools sc ON sc.id=ai.school_id WHERE ss.token_hash=$1 AND ss.revoked_at IS NULL AND ss.expires_at>now() AND ai.status='ACTIVE'`,h(token)).Scan(&p.IdentityID,&p.Role,&p.GuardianPublicID,&p.SchoolPublicID);return p,e}
