package billing

import (
 "context"
 "fmt"
 "strings"
 "time"

 "github.com/jackc/pgx/v5/pgxpool"
)

type Service struct{db *pgxpool.Pool}
func NewService(db *pgxpool.Pool)*Service{return &Service{db:db}}

type FeeSchedule struct{ID string `json:"id"`;SchoolID string `json:"school_id"`;SchoolYearID string `json:"school_year_id"`;Name string `json:"name"`;Currency string `json:"currency"`;Status string `json:"status"`}
type CreateFeeScheduleInput struct{SchoolPublicID string `json:"school_public_id"`;SchoolYearID string `json:"school_year_id"`;LevelID string `json:"level_id"`;ClassID string `json:"class_id"`;Name string `json:"name"`}
type FeeItem struct{ID string `json:"id"`;FeeScheduleID string `json:"fee_schedule_id"`;Code string `json:"code"`;Label string `json:"label"`;Amount int64 `json:"amount"`;Mandatory bool `json:"mandatory"`}
type CreateFeeItemInput struct{FeeScheduleID string `json:"fee_schedule_id"`;Code string `json:"code"`;Label string `json:"label"`;Amount int64 `json:"amount"`;Mandatory bool `json:"mandatory"`;Refundable bool `json:"refundable"`;DisplayOrder int `json:"display_order"`}
type InstallmentPlan struct{ID string `json:"id"`;FeeScheduleID string `json:"fee_schedule_id"`;Name string `json:"name"`;AllowPartialPayment bool `json:"allow_partial_payment"`}
type CreatePlanInput struct{FeeScheduleID string `json:"fee_schedule_id"`;Name string `json:"name"`;AllowPartialPayment bool `json:"allow_partial_payment"`}
type Installment struct{ID string `json:"id"`;PlanID string `json:"installment_plan_id"`;Sequence int `json:"sequence"`;Label string `json:"label"`;Amount int64 `json:"amount"`;DueDate time.Time `json:"due_date"`}
type CreateInstallmentInput struct{PlanID string `json:"installment_plan_id"`;Sequence int `json:"sequence"`;Label string `json:"label"`;Amount int64 `json:"amount"`;DueDate string `json:"due_date"`}
type ActivateEnrollmentInput struct{SchoolPublicID string `json:"school_public_id"`;EnrollmentPublicID string `json:"enrollment_public_id"`;FeeScheduleID string `json:"fee_schedule_id"`;InstallmentPlanID string `json:"installment_plan_id"`}
type ActivationResult struct{EnrollmentPublicID string `json:"enrollment_public_id"`;Status string `json:"status"`;ChargesCreated int64 `json:"charges_created"`;TotalAmount int64 `json:"total_amount"`}

func(s *Service)CreateFeeSchedule(ctx context.Context,in CreateFeeScheduleInput)(FeeSchedule,error){if strings.TrimSpace(in.Name)==""{return FeeSchedule{},fmt.Errorf("name is required")};if in.LevelID==""&&in.ClassID==""{return FeeSchedule{},fmt.Errorf("level_id or class_id is required")};var out FeeSchedule;err:=s.db.QueryRow(ctx,`INSERT INTO fee_schedules(school_id,school_year_id,level_id,class_id,name) SELECT s.id,sy.id,NULLIF($3,'')::uuid,NULLIF($4,'')::uuid,$5 FROM schools s JOIN school_years sy ON sy.id=$2::uuid AND sy.school_id=s.id WHERE s.public_id=$1 AND (NULLIF($3,'') IS NULL OR EXISTS(SELECT 1 FROM levels l WHERE l.id=$3::uuid AND l.school_id=s.id)) AND (NULLIF($4,'') IS NULL OR EXISTS(SELECT 1 FROM classes c WHERE c.id=$4::uuid AND c.school_id=s.id AND c.school_year_id=sy.id)) RETURNING id::text,school_id::text,school_year_id::text,name,currency,status`,in.SchoolPublicID,in.SchoolYearID,in.LevelID,in.ClassID,in.Name).Scan(&out.ID,&out.SchoolID,&out.SchoolYearID,&out.Name,&out.Currency,&out.Status);return out,err}
func(s *Service)CreateFeeItem(ctx context.Context,in CreateFeeItemInput)(FeeItem,error){if in.Amount<0||in.Code==""||in.Label==""{return FeeItem{},fmt.Errorf("valid code, label and amount are required")};var out FeeItem;err:=s.db.QueryRow(ctx,`INSERT INTO fee_items(fee_schedule_id,code,label,amount,mandatory,refundable,display_order) VALUES($1::uuid,$2,$3,$4,$5,$6,$7) RETURNING id::text,fee_schedule_id::text,code,label,amount,mandatory`,in.FeeScheduleID,in.Code,in.Label,in.Amount,in.Mandatory,in.Refundable,in.DisplayOrder).Scan(&out.ID,&out.FeeScheduleID,&out.Code,&out.Label,&out.Amount,&out.Mandatory);return out,err}
func(s *Service)CreatePlan(ctx context.Context,in CreatePlanInput)(InstallmentPlan,error){var out InstallmentPlan;err:=s.db.QueryRow(ctx,`INSERT INTO installment_plans(fee_schedule_id,name,allow_partial_payment) VALUES($1::uuid,$2,$3) RETURNING id::text,fee_schedule_id::text,name,allow_partial_payment`,in.FeeScheduleID,in.Name,in.AllowPartialPayment).Scan(&out.ID,&out.FeeScheduleID,&out.Name,&out.AllowPartialPayment);return out,err}
func(s *Service)CreateInstallment(ctx context.Context,in CreateInstallmentInput)(Installment,error){due,err:=time.Parse("2006-01-02",in.DueDate);if err!=nil{return Installment{},fmt.Errorf("invalid due_date")};if in.Sequence<1||in.Amount<0{return Installment{},fmt.Errorf("invalid sequence or amount")};var out Installment;err=s.db.QueryRow(ctx,`INSERT INTO installments(installment_plan_id,sequence,label,amount,due_date) VALUES($1::uuid,$2,$3,$4,$5) RETURNING id::text,installment_plan_id::text,sequence,label,amount,due_date`,in.PlanID,in.Sequence,in.Label,in.Amount,due).Scan(&out.ID,&out.PlanID,&out.Sequence,&out.Label,&out.Amount,&out.DueDate);return out,err}

func(s *Service)ActivateEnrollment(ctx context.Context,in ActivateEnrollmentInput)(ActivationResult,error){tx,err:=s.db.Begin(ctx);if err!=nil{return ActivationResult{},err};defer tx.Rollback(ctx)
 var enrollmentID,studentID,schoolID,classID,levelID,schoolYearID,status string
 err=tx.QueryRow(ctx,`SELECT e.id::text,e.student_id::text,e.school_id::text,e.class_id::text,c.level_id::text,e.school_year_id::text,e.status FROM enrollments e JOIN schools s ON s.id=e.school_id JOIN classes c ON c.id=e.class_id WHERE s.public_id=$1 AND e.public_id=$2 FOR UPDATE`,in.SchoolPublicID,in.EnrollmentPublicID).Scan(&enrollmentID,&studentID,&schoolID,&classID,&levelID,&schoolYearID,&status);if err!=nil{return ActivationResult{},err};if status=="ACTIVE"{return ActivationResult{},fmt.Errorf("enrollment already active")}
 var scheduleYear,scheduleSchool string;var scheduleLevel,scheduleClass *string
 err=tx.QueryRow(ctx,`SELECT school_year_id::text,school_id::text,level_id::text,class_id::text FROM fee_schedules WHERE id=$1::uuid AND status IN('DRAFT','ACTIVE')`,in.FeeScheduleID).Scan(&scheduleYear,&scheduleSchool,&scheduleLevel,&scheduleClass);if err!=nil{return ActivationResult{},err};if scheduleYear!=schoolYearID||scheduleSchool!=schoolID{return ActivationResult{},fmt.Errorf("fee schedule does not belong to enrollment tenant/year")};if scheduleClass!=nil&&*scheduleClass!=classID{return ActivationResult{},fmt.Errorf("fee schedule does not apply to class")};if scheduleClass==nil&&(scheduleLevel==nil||*scheduleLevel!=levelID){return ActivationResult{},fmt.Errorf("fee schedule does not apply to level")}
 var planSchedule string;err=tx.QueryRow(ctx,`SELECT fee_schedule_id::text FROM installment_plans WHERE id=$1::uuid`,in.InstallmentPlanID).Scan(&planSchedule);if err!=nil{return ActivationResult{},err};if planSchedule!=in.FeeScheduleID{return ActivationResult{},fmt.Errorf("installment plan does not belong to fee schedule")}
 var itemTotal,installmentTotal int64;_ = tx.QueryRow(ctx,`SELECT COALESCE(sum(amount),0) FROM fee_items WHERE fee_schedule_id=$1::uuid AND mandatory=true`,in.FeeScheduleID).Scan(&itemTotal);_ = tx.QueryRow(ctx,`SELECT COALESCE(sum(amount),0) FROM installments WHERE installment_plan_id=$1::uuid`,in.InstallmentPlanID).Scan(&installmentTotal);if itemTotal<=0{return ActivationResult{},fmt.Errorf("fee schedule has no mandatory fees")};if itemTotal!=installmentTotal{return ActivationResult{},fmt.Errorf("installment total %d does not match mandatory fee total %d",installmentTotal,itemTotal)}
 tag,err:=tx.Exec(ctx,`INSERT INTO student_charges(school_id,student_id,enrollment_id,installment_id,label,original_amount,net_amount,balance,due_date,status) SELECT $1::uuid,$2::uuid,$3::uuid,i.id,i.label,i.amount,i.amount,i.amount,i.due_date,CASE WHEN i.due_date<CURRENT_DATE THEN 'OVERDUE' WHEN i.due_date=CURRENT_DATE THEN 'DUE' ELSE 'UPCOMING' END FROM installments i WHERE i.installment_plan_id=$4::uuid`,schoolID,studentID,enrollmentID,in.InstallmentPlanID);if err!=nil{return ActivationResult{},err};if tag.RowsAffected()==0{return ActivationResult{},fmt.Errorf("installment plan has no installments")}
 _,err=tx.Exec(ctx,`UPDATE enrollments SET status='ACTIVE',validated_at=now(),updated_at=now() WHERE id=$1::uuid`,enrollmentID);if err!=nil{return ActivationResult{},err};if err=tx.Commit(ctx);err!=nil{return ActivationResult{},err};return ActivationResult{EnrollmentPublicID:in.EnrollmentPublicID,Status:"ACTIVE",ChargesCreated:tag.RowsAffected(),TotalAmount:installmentTotal},nil}
